=pod

=encoding UTF-8

=head1 NAME

Mail::Chimp3 - an interface to MailChimp's RESTful Web API v3 using Web::API

=head1 VERSION

version 0.01

=head1 SYNOPSIS

This is for the MailChimp API v3.0.

Please refer to the API documentation at 
L<http://developer.mailchimp.com/documentation/mailchimp/reference/overview/>

    use Mail::Chimp3;

    my $mailchimp = Mail::Chimp3->new(
        api_key => $apikey,
    );

    my $response = $mailchimp->add_store(
        store_id => '123',
        cart_id  => '456',
    );

=head1 SUBROUTINES/METHODS

=head2 add_authorized_app

=head2 add_automation_subscriber

=head2 add_batch

=head2 add_cart

=head2 add_cart_line

=head2 add_customer

=head2 add_list

=head2 add_member

=head2 add_merge_field

=head2 add_order

=head2 add_order_line

=head2 add_product

=head2 add_segment

=head2 add_store

=head2 add_variant

=head2 authorized_apps

=head2 automation_emails

=head2 automations

=head2 automation_subscribers

=head2 batches

=head2 cart_lines

=head2 carts

=head2 conversations

=head2 customers

=head2 delete_batch

=head2 delete_cart

=head2 delete_cart_line

=head2 delete_customer

=head2 delete_list

=head2 delete_member

=head2 delete_merge_field

=head2 delete_order

=head2 delete_order_line

=head2 delete_product

=head2 delete_segment

=head2 delete_store

=head2 delete_variant

=head2 delete_list

=head2 members

=head2 merge_fields

=head2 order_lines

=head2 orders

=head2 pause_automation

=head2 pause_automation_email

=head2 delete_store

=head2 delete_variant

=head2 removed_automation_subscribers

=head2 root

=head2 segments

=head2 removed_automation_subscribers

=head2 start_automation_email

=head2 stores

=head2 update_cart

=head2 update_cart_line

=head2 update_customer

=head2 update_list

=head2 update_member

=head2 update_merge_field

=head2 update_order

=head2 update_order_line

=head2 update_segment

=head2 update_store

=head2 update_variant

=head2 upsert_customer

=head2 upsert_member

=head2 upsert_variant

=head2 variants

=head1 INTERNALS

=head2 BUILD

basic configuration for the client API happens usually in the BUILD method when using Web::API

=head1 BUGS

Please report any bugs or feature requests on GitHub's issue tracker L<https://github.com/jdigory/p5-Mail-Chimp3/issues>.

=head1 SUPPORT

You can find documentation for this module with the perldoc command.

    perldoc Mail::Chimp3

You can also look for information at:

=over 4

=item * GitHub repository

L<https://github.com/jdigory/p5-Mail-Chimp3>

=back

=head1 AUTHOR

Josh Lavin

=cut
